### ISSUE TITLE
개발 서버 (develop 브랜치)

### ISSUE THREAD

**Issue by wonslee** [uswLectureEvaluation/SUWIKI-Spring#36]
시간표 API 개발 이전에 최대한 안전하게 하고 싶어서 개발용 서버를 따로 두려고 합니다
용도는 QA 테스트 및 전체적인 정상동작 여부 테스트입니다
진욱님께서 APK 따로 만들어주시고 다 같이 체크한 후에 main 브랜치 로 병합, 운영 서버에 배포하는 흐름이예요

개발용 브랜치명을 develop으로 두려고 하는데 괜찮을까요 도현님? @K-Diger 
main -> develop ->  feature/... 브랜치에서 작업

### TODO
- [x] 개발용 AWS 계정 생성 및 인스턴스 설정
- [x] 노션에 공유

**Comment by K-Diger** [comment]
기존 저희랑 사용하는 브랜치 전략이랑 동일해서 문제될 것 없습니다. 

좋습니다~! 고생해주세요...!

**Comment by wonslee** [comment]
디폴트 브랜치는 develop 브랜치로 바꾸겠습니다!
