### ISSUE TITLE
메일 인증 - 개발 서버 QA를 위한 인증 링크 URL 로직 변경 및 리팩토링

### ISSUE THREAD

**Issue by wonslee** [uswLectureEvaluation/SUWIKI-Spring#66]
## 문제 정의
현재 메일 인증 링크는 [상수로 관리](https://github.com/uswLectureEvaluation/SUWIKI-Spring/blob/002c0d8ef37ea5a22b4d67bcade07e20c6ff703c/src/main/java/usw/suwiki/domain/user/user/service/UserBusinessService.java#L55)되어, 항상 운영 서버(=>운영 DB)를 향하는 상태입니다.

당장 수위키 서비스에는 문제 없지만, 개발 서버에서 회원가입 플로우를 QA할 때 문제가 발생합니다. 
개발 서버(및 로컬 서버)가 운영 DB의 상태에 영향 받기 때문입니다.

![image](https://github.com/uswLectureEvaluation/SUWIKI-Spring/assets/72124326/c1384b54-aaf6-44ce-a3c6-42bacae7bc61)
![image](https://github.com/uswLectureEvaluation/SUWIKI-Spring/assets/72124326/ade3c67a-a5d6-4f18-a427-a13032531298)

수원대 웹 메일은 학생당 한 계정씩만 생성 가능하기 때문에, 한번 계정을 생성한 이상 같은 메일 혹은 아이디로는 회원가입에 성공할 수 없습니다.
그래서 개발시 편의상 DB의 레코드를 삭제시켜주는데, 운영 DB를 대상으로 하기에는 위험하다고 생각합니다.

## 고민들
처음에는 단순히 개발 서버 URI 상수를 추가해서 올려볼까 생각했지만, 그렇게 되면 개발에서 운영 서버로 release할 때 매번 수정해야 하고, 만약 휴먼 에러가 발생하면 운영 서비스가 정상 작동하지 않을 수 있다고 생각했습니다. 그래서 상수화는 배제했습니다.

생각해본 해결 방법은 2가지입니다
1. 서버 URI를 yml 프로퍼티로 관리
2. HTTPServletRequest 객체 이용

yml 프로퍼티로 관리하는 방법은 명시적이고 편리하다고 생각합니다. 그러나 문제점은 서버의 URI 혹은 도메인 주소가 변할 경우 yml 프로퍼티도 수정해야 한다는 것입니다. 휴면 에러의 가능성이 있습니다. (사실 이 방법도 나쁘지는 않다고 생각합니다.)

HTTPServletRequest 방법은 컨트롤러에서 받은 요청 URI에서 요청한 서버의 IP(도메인 주소)와 포트 번호 및 통신 프로토콜을 (http or https) 가져오고, 메일 인증 API의 URI로 변환시켜주는 방법입니다.
이 방법은 위의 문제를 해결하며 서버의 URI 변화에 영향 받지 않는다는 장점이 있습니다. 

## 문제 해결 (진행중)

HTTP ServletRequest 방법으로 진행중입니다.

코드가 조금 길어져서, 조금 더 우아한 방법은 없을지 찾아보는 중입니다,,

**Comment by Hejow** [comment]
좋은 고민을 하고 계신 것 같아서 아이디어 하나 드릴게요!

말씀하신 대로 `HTTPServletRequest`은 비용(시간, 코드)이 생각보다 많이 발생합니다.
그래서, yml 기반으로 두고 `@ConfigurationProperties`를 활용한 provider 객체를 만들어
필요한 곳에서 composition 해서 사용하신다면 말씀하신 문제가 쉽게 해결될 것 같네요!!

**Comment by wonslee** [comment]
희조님 너무 감사합니다!
`@ConfigurationProperties`에 대해 공부해보게 됐습니다.
프로퍼티들을 객체지향적으로 쓸 수 있다는게 큰 장점이라고 생각해서 반영하고 PR 올릴께요!

**Comment by wonslee** [comment]
@Hejow 이전 PR 리뷰 주신 내용 반영해서 머지했습니다. 그런데 고민이 하나 있습니다!

Properties 객체를 어디에서 다뤄야하는지에 대한 고민입니다.

현재는 `BuildEmailAuthForm` 객체가 컴포넌트로 등록되어 있어서 스프링측에서 프로퍼티 객체를 DI 해줄 수 있습니다.

그러나 희조님께서 이전에 말씀하신 것처럼 만약에 `BuildEmailAuthForm` 객체를 컴포넌트 관리 대상에서 제외시킨다면, 더 이상 생성자 DI를 받지 못하기 때문에 기존의 방법처럼 프로퍼티 객체를 필드로 갖고 있기는 어려워집니다. (혹은 방법이 있을까요? )

더 이상 컴포넌트가 아닌 상황을 가정했을 때, 제가 생각해본 방법은
1. ApplicationContext.getBean을 통해 프로퍼티 객체를 문자열로 찾기
2. 외부(Service)에서 DI를 받아 필요한 값을 인자로 전달
 
정도네요.. 좋은 방법이 있을까요?

**Comment by Hejow** [comment]
@wonslee 
여쭤봐주신 내용은 `enum`으로도 해결할 수 있을 것 같습니다.
`@Component`로 등록된 객체는 default로 싱글톤의 성질을 가지고(scope에 따라 다르게 설정이 가능합니다.) 프레임워크에서 자동적으로 DI를 해줄 수 있다는 장점이 존재합니다.

하지만 **컴포넌트로 등록되었다는 것은 특정한 역할을 수행한다**를 의미합니다. 
다르게 표현하면 데이터(혹은 자료구조)가 아닌 객체로서 바라봄을 의미합니다. 근데 다양한 `Form`은 **단순 데이터에 불과**합니다. 

따라서, 데이터의 열거형인 enum으로 관리한다면 싱글톤으로도 잘 관리할 수 있습니다.
jvm 관점에서 바라보면 동일한 메모리를 가지고, application context 입장에서 보았을 때는 오히려 관리해야할 bean의 개수가 줄어듦을 의미합니다.

따라서, enum으로 분리하고 관심사에 맞게 관리한다면 의존성을 폭발적으로 줄일 수 있어 보입니다.
예를 들어서, 기존에 `ServerProperties`를 실질적으로 메일을 전송하는 쪽에서 관리함으로 `UserBusinessService`의 코드량이 많이 줄어든 것을 체감하셨을 겁니다.
비슷하게 관심사를 고려하시면 넓게 퍼져있는 의존성을 하나의 엔드 포인트에서 관리할 수 있고 그에 따라 코드량이 엄청나게 줄어들 수도, 의존성을 줄일 수도 있습니다!

**Comment by wonslee** [comment]
오호...! 
너무 좋은 인사이트 감사합니다. :rocket: 
Component 등록 기준과 싱글톤 패턴 대해 조금 더 고민해보게 됐습니다.

말씀해주신 싱글톤 패턴 혹은 템플릿 메서드 패턴으로 의존성을 줄이고, 서비스에서 프로퍼티 객체 의존성을 추가하는 방식으로 리팩토링해보겠습니다.
감사합니다 희조님!
