### ISSUE TITLE
CORS 허용 로직, JWT 인증 로직에 대한 filter 적용

### ISSUE THREAD

**Issue by wonslee** [uswLectureEvaluation/SUWIKI-Spring#74]
컨트롤러마다 반복되는 코드들에 대해서 filter을 적용하여 관심사를 분리하려고 합니다. 

VersionController에서 CORS가 적용되지 않았던 문제(`@CrossOrigin` 누락)가 있었는데 임시방편으로 해당 어노테이션 추가해둔 상태입니다.  
추후 리팩토링 예정입니다.

**Comment by Hejow** [comment]
지금 봤는데 하나의 엔드포인트를 두고 관리하면 편할 것 같아요!
이거는 스프링에서 자체적으로 지원도 해주잖아요!?
